# Generated by Django 3.0.8 on 2020-07-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_auto_20200721_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='category',
            field=models.CharField(choices=[('Non-Bank', 'Non-Bank'), ('Universal Bank', 'Universal, Bank'), ('Savings/Thrift Bank', 'Savings/Thrift Bank'), ('Rural Bank', 'Rural Bank'), ('Coop Bank', 'Coop Bank'), ('Cooperative', 'Cooperative'), ('Private Financing', 'Private Financing')], max_length=100),
        ),
    ]
