# Generated by Django 3.0.8 on 2020-07-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_auto_20200721_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='category',
            field=models.CharField(choices=[('Non-Bank', 'Non-Bank'), ('Universal Bank', 'Universal Bank'), ('Savings/Thrift Bank', 'Savings/Thrift Bank'), ('Rural Bank', 'Rural Bank'), ('Coop Bank', 'Coop Bank'), ('Cooperative', 'Cooperative'), ('Private Financing', 'Private Financing')], max_length=100),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.Bank')),
            ],
        ),
    ]
