# Generated by Django 3.0.8 on 2020-07-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_auto_20200721_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('bank', 'branch')},
        ),
    ]
