# Generated by Django 3.0.8 on 2020-07-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_auto_20200722_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
