# Generated by Django 3.0.8 on 2020-07-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('Employed', 'Employed'), ('Non-Employed', 'Non-Employed'), ('OFW', 'OFW'), ('Pensioners', 'Pensioners'), ('Other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'unique_together': {('document', 'employment_type')},
            },
        ),
    ]
