# Generated by Django 3.0.8 on 2020-07-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_auto_20200722_1644'),
        ('documents', '0002_collateral'),
        ('loans', '0002_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('min_loan_amount', models.IntegerField()),
                ('max_loan_amount', models.IntegerField()),
                ('computation', models.CharField(choices=[('Balloon', 'Balloon'), ('Add On', 'Add On'), ('Diminishing', 'Diminishing')], max_length=100)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('min_income', models.IntegerField()),
                ('min_tenure', models.IntegerField()),
                ('agreement', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.Bank')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Classification')),
                ('collaterals', models.ManyToManyField(to='documents.Collateral')),
                ('documents', models.ManyToManyField(to='documents.Document')),
            ],
        ),
    ]
