# Generated by Django 3.0.8 on 2020-07-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='agreement',
            field=models.FileField(upload_to=''),
        ),
    ]
